# Site settings 配置站点
title: '以太经典_ETC'
description: '介绍以太经典ETC的最新资讯，包括技术，团队和社区，为大家呈现最全面的Ethereum_Classic'
keyword: '以太经典ETC,技术进度,项目进展,中国社区,国际社区,核心开发团队'
url: 'http://ethereumclassic.cn' # your host
sponsor: 哥德尔实验室Gödel Labs
sponsorContact: Contact@godel.ai


# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  首页: '/'
  资讯: '/tags.html'

# Footer
footer:
  since: ETCChina

# Author 配置博主信息
author: '以太经典_ETC'
nickname: 'ETC'
bio: '介绍以太经典ETC的最新资讯，包括技术，团队和社区，为大家呈现最全面的Ethereum_Classic'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

#intensedebate 评论功能
intensedebate_comments: true

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'twitter', 'facebook']
#social-share-items: ['wechat', 'weibo', 'twitter', 'facebook', 'telegram']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'seaOfClouds'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/ethereumclassic'
  jianshu: '//www.jianshu.com/u/11c1ad5e8788'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 10
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

#sass file
sass:
    style: compressed

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
